# Generated by Django 3.1.5 on 2021-02-27 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0005_codebase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codebase',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code', to='contenttypes.contenttype'),
        ),
    ]
