# Generated by Django 3.1.5 on 2021-03-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210312_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='privilege',
            field=models.SmallIntegerField(default=4, null=True),
        ),
    ]
