# Generated by Django 3.1.5 on 2021-02-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20210131_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='courses',
            field=models.ManyToManyField(related_name='StudentProfile', to='students.Course'),
        ),
    ]
