# Generated by Django 3.1.5 on 2021-02-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20210202_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='is_flaged',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
