# Generated by Django 3.1.5 on 2021-02-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_studentprofile_last_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
