# Generated by Django 3.1.5 on 2021-02-28 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_studentprofile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='rfid_code',
        ),
    ]
