# Generated by Django 3.1.5 on 2021-06-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20210312_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credit_unit',
            field=models.IntegerField(null=True),
        ),
    ]
