# Generated by Django 3.1.5 on 2021-02-21 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.BigIntegerField(null=True, unique=True)),
                ('surname', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('other_name', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('lga', models.CharField(max_length=50, null=True)),
                ('state_of_origin', models.CharField(max_length=20, null=True)),
                ('nationality', models.CharField(max_length=20, null=True)),
                ('photo', models.ImageField(null=True, upload_to='image/')),
                ('rfid_code', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('department', models.CharField(max_length=255, null=True)),
                ('designation', models.CharField(max_length=255, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('first_name',),
            },
        ),
        migrations.CreateModel(
            name='StaffWorkAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_in_time', models.DateTimeField(auto_now_add=True)),
                ('sign_out_time', models.DateTimeField(null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_work_attendance', to='staff.staffprofile')),
            ],
            options={
                'ordering': ('sign_in_time',),
            },
        ),
    ]
