# Generated by Django 3.1.5 on 2021-03-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_staffprofile_id_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffprofile',
            old_name='id_number',
            new_name='staff_id_number',
        ),
    ]
