# Generated by Django 3.1.5 on 2021-08-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_scanrecords'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='is_flaged',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scanrecords',
            name='location',
            field=models.CharField(blank=True, default='T.Y Buratai Gate', max_length=50, null=True),
        ),
    ]
