# Generated by Django 3.1.5 on 2021-02-13 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0005_auto_20210202_0606'),
        ('exams', '0002_auto_20210202_0606'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('approved_start_time', models.DateTimeField()),
                ('approved_stop_time', models.DateTimeField()),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examination_request_approval', to=settings.AUTH_USER_MODEL)),
                ('course', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examination_request', to='students.course')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examination_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('course',),
            },
        ),
    ]
