# Generated by Django 3.1.5 on 2021-02-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_examinationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinationrequest',
            name='approved_start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='examinationrequest',
            name='approved_stop_time',
            field=models.DateTimeField(null=True),
        ),
    ]
