# Generated by Django 3.1.5 on 2021-02-18 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_auto_20210213_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examinationrequest',
            options={'ordering': ('status',)},
        ),
    ]
