# Generated by Django 3.1.5 on 2021-02-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_auto_20210218_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examinationrequest',
            options={'ordering': ('request_date',)},
        ),
    ]
