# Generated by Django 3.1.5 on 2021-03-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20210303_1443'),
        ('exams', '0006_auto_20210226_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationrequest',
            name='invigilators',
            field=models.ManyToManyField(related_name='examination_request', to='staff.StaffProfile'),
        ),
    ]
