# Generated by Django 3.1.5 on 2021-03-07 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20210303_1443'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0008_auto_20210307_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesheet',
            name='sign_out_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='invigilatorattendancesheet',
            name='sign_out_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='ExaminationMalpractice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_act', models.DateTimeField(auto_now_add=True)),
                ('details', models.CharField(blank=True, max_length=1000, null=True)),
                ('exhibit', models.FileField(null=True, upload_to='files/')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_malpractice', to='students.course')),
                ('invigilator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_malpractice', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_malpractice', to='students.studentprofile')),
            ],
            options={
                'ordering': ('student',),
            },
        ),
    ]
