# Generated by Django 3.1.5 on 2021-03-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_auto_20210307_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinationmalpractice',
            name='exhibit',
            field=models.FileField(null=True, upload_to='file/'),
        ),
    ]
