# Generated by Django 4.0.4 on 2022-05-24 06:45

from django.db import migrations
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_auto_20210808_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesheet',
            name='sign_in_time',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancesheet',
            name='sign_out_time',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True, null=True),
        ),
    ]
