# Generated by Django 4.0.4 on 2022-05-24 13:35

from django.db import migrations
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_alter_attendancesheet_sign_in_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesheet',
            name='sign_in_time',
            field=unixtimestampfield.fields.UnixTimeStampField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancesheet',
            name='sign_out_time',
            field=unixtimestampfield.fields.UnixTimeStampField(blank=True, null=True),
        ),
    ]
